# Extra env variables
# env = MY_GLOBAL_ENV,setting
# Set Omarchy screenshot directory
env = OMARCHY_SCREENSHOT_DIR,$HOME/Documents/Temporary/screenshots

# Set Omarchy recordings directory
env = OMARCHY_SCREENRECORD_DIR,$HOME/Documents/Temporary/recordings/raw
