imports:
  - "./matches/globals/paste_clipboard.yml"
  - "./matches/globals/words.yml"
  - "./matches/globals/datetime/date_time.yml"
  - "./matches/globals/datetime/days.yml"
  - "./matches/globals/datetime/months.yml"
  - "./matches/globals/datetime/nxtweek.yml"
  - "./matches/globals/datetime/week_of.yml"
  - "./matches/globals/datetime/weekdays.yml"
  - "./matches/globals/datetime/weekly.yml"
  - "./matches/globals/datetime/wkago.yml"
  - "./matches/globals/datetime/yst_tmr.yml"
  - "./matches/personal/personal_info.yml"
  - "./matches/variables/adjustable/email/addongreeting.yml"
  - "./matches/variables/adjustable/email/assigned.yml"
  - "./matches/variables/adjustable/email/checkup.yml"
  - "./matches/variables/adjustable/email/completedwork.yml"
  - "./matches/variables/adjustable/email/deadlines.yml"
  - "./matches/variables/adjustable/email/followup.yml"
  - "./matches/variables/adjustable/email/greeting.yml"
  - "./matches/variables/adjustable/email/missappnovm.yml"
  - "./matches/variables/adjustable/email/missappvm.yml"
  - "./matches/variables/adjustable/email/nolongerreqass.yml"
  - "./matches/variables/adjustable/email/noresponse.yml"
  - "./matches/variables/adjustable/email/notification.yml"
  - "./matches/variables/adjustable/email/novoicemail.yml"
  - "./matches/variables/adjustable/email/novmfollowup.yml"
  - "./matches/variables/adjustable/email/quotes.yml"
  - "./matches/variables/adjustable/email/reqresponse.yml"
  - "./matches/variables/adjustable/email/setappointment.yml"
  - "./matches/variables/adjustable/email/signoffs.yml"
  - "./matches/variables/adjustable/email/stillreqass.yml"
  - "./matches/variables/adjustable/email/thanking.yml"
  - "./matches/variables/adjustable/email/voicemail.yml"
  - "./matches/variables/static/assornoass.yml"
  - "./matches/variables/static/company.yml"
  - "./matches/variables/static/date.yml"
  - "./matches/variables/static/phone_numbers.yml"
  - "./matches/variables/static/signature.yml"
  - "./matches/work/client_specific/credentials.yml"
  - "./matches/work/dispatch/dispatch_emails.yml"
  - "./matches/work/dispatch/dispatch_templates.yml"
  - "./matches/work/email_blocks/dtemail.yml"
  - "./matches/work/email_blocks/greetings.yml"
  - "./matches/work/email_blocks/onetimeuse.yml"
  - "./matches/work/email_blocks/signature.yml"
  - "./matches/work/emails/emails.yml"
  - "./matches/work/names/clients.yml"
